sudo: required
services: 
  - docker

before_install:
  - docker build -t tsa/docker-message-postgres -f Dockerfile.dev .

script:
  - docker run tsa/docker-message-postgres npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-message-postgres"
  env: "DockerMessagePostgres-env"
  bucket_name: "elasticbeanstalk-us-east-2-561864422029"
  bucket_path: "docker-message-postgres"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRECT_KEY
